### ISSUE TITLE
Error: app.lookup is not a function

### ISSUE THREAD

**Issue by bmbariah** [touch4it/feathers-rabbit-queue#6]
I'm getting the above error when running createMessage()
Using the latest feathersJS.
Tried updating both rabbit-queue & amqplib libs.

I've  traced the issue to this line in index.js 
````Javascript 
const { routing } = require('@feathersjs/transport-commons/lib/routing');

Sample  Logs

| Got error: Error: app.lookup is not a function
0|api    |     at onReply (/app/node_modules/rabbit-queue/js/reply-queue.js:68:22)
0|api    |     at ConfirmChannel.BaseChannel.dispatchMessage (/app/node_modules/amqplib/lib/channel.js:484:12)
0|api    |     at ConfirmChannel.BaseChannel.handleDelivery (/app/node_modules/amqplib/lib/channel.js:493:15)
0|api    |     at ConfirmChannel.emit (events.js:311:20)
0|api    |     at /app/node_modules/amqplib/lib/channel.js:279:10
0|api    |     at ConfirmChannel.content (/app/node_modules/amqplib/lib/channel.js:332:9)
0|api    |     at ConfirmChannel.C.acceptMessageFrame (/app/node_modules/amqplib/lib/channel.js:247:31)
0|api    |     at ConfirmChannel.C.accept (/app/node_modules/amqplib/lib/channel.js:400:17)
0|api    |     at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
0|api    |     at Socket.go (/app/node_modules/amqplib/lib/connection.js:478:48)
0|api    |     at Socket.emit (events.js:311:20)
0|api    |     at emitReadable_ (_stream_readable.js:562:12)
0|api    |     at processTicksAndRejections (internal/process/task_queues.js:83:21)

`

**Comment by bmbariah** [comment]
Fixed with the pull requestfrom @Pato1

````Javascript
const {routing} = require('@feathersjs/transport-commons');
